projects:
  - project_id: de0002-poc-fdac-0
    zone: europe-west3-a
    tags_assertion: True
    label_assertion: True
    object_versioning_assertion: True
    public_access_assertion: True
    access_control_assertion: Uniform # FineGrained
    location_assertion: true
    location_type_assertion: true
    storage_class_assertion: True